//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Score
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreDetail
    {
        public int ScoreDetailID { get; set; }
        public int ScoreHeaderID { get; set; }
        public int SubjectID { get; set; }
        public int Score { get; set; }
        public string Status { get; set; }
    
        public virtual ScoreHeader ScoreHeader { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
