//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Score
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.ScoreHeaders = new HashSet<ScoreHeader>();
        }
    
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string StudentClass { get; set; }
    
        public virtual ICollection<ScoreHeader> ScoreHeaders { get; set; }
    }
}
