//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Score
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.ScoreDetails = new HashSet<ScoreDetail>();
        }
    
        public int SubjectID { get; set; }
        public string SubjectName { get; set; }
        public int MinimumCriteria { get; set; }
        public string IsPractice { get; set; }
    
        public virtual ICollection<ScoreDetail> ScoreDetails { get; set; }
    }
}
