//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyConvert
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public Currency()
        {
            this.USDExchangeRates = new HashSet<USDExchangeRate>();
        }
    
        public int id { get; set; }
        public string country { get; set; }
        public string name { get; set; }
        public string abbreviation { get; set; }
    
        public virtual ICollection<USDExchangeRate> USDExchangeRates { get; set; }
    }
}
